markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Saba Khalilnaji
production_url : http://somesaba.github.io
description: "Thoughts, projects, ideas and more from Saba Khalilnaji."
disqus_shortname: somesabablog
analytics: UA-41345406-1
gauges:
author :
  name : Saba Khalilnaji
  github : somesaba
  linkedin : pub/saba-khalilnaji/25/544/7a5/
  email: somesaba@gmail.com
